spring:
  application:
    name: demo-customer
  profiles:
    active: ${ENVIRONMENT:development}
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    testOnBorrow: true
    connectionTimeout: 120000
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true  #stops angry clob error on startup
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO} # none, update
    open-in-view: false

customer:
  image:
    image_folder: ${IMAGE_FOLDER}
    url_path: ${URL_PATH}

hibernate:
  jdbc:
    lob:
      non_contextual_creation: true #stops angry clob error on startup

server:
  port: 8081
  compression:
    enabled: true
    mime-types:
      - application/json

logging:
  level:
    com.agile.monkeys.demo: INFO

#endpoints:
#  loggers:
#    sensitive: false # opening them on port 8081


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: false
  info:
    git:
      mode: full

---
spring:
  config:
    activate:
      on-profile: production
---
spring:
  jpa:
    show-sql: true
  config:
    activate:
      on-profile: development

---
spring:
  config:
    activate:
      on-profile: development, stage

logging:
  level:
    org.hibernate: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.cache: DEBUG
    org.hibernate.stat: DEBUG
    com.agile.monkeys.demo: DEBUG
---
spring:
  config:
    activate:
      on-profile: production, stage

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db_test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop

customer:
  image:
    image_folder: ./tmp_test/
    url_path: /image-data