version: '2'

services:
  db:
    container_name: demo-db
#    image: 'postgres:13.1-alpine'
    image: 'postgres:9.4'
    env_file: ./.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  app:
    depends_on:
      - db
    container_name: demo-app
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=$SPRING_JPA_HIBERNATE_DDL_AUTO
