version: '2'

services:
  db:
    container_name: demo-db
    image: 'postgres:9.4'
    env_file: ./.env
    restart: unless-stopped
    ports:
      - $DB_DOCKER_PORT_MAPPING
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  app:
    depends_on:
      - db
    container_name: customer-app
    image: 'customer-app:latest'
    env_file: ./.env
    ports:
      - $APP_DOCKER_PORT_MAPPING
    volumes:
      - image-data:$IMAGE_FOLDER
      - $HOME/.m2/repository:/root/.m2/repository
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/$POSTGRES_DB
      - SPRING_DATASOURCE_USERNAME=$POSTGRES_USER
      - SPRING_DATASOURCE_PASSWORD=$POSTGRES_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=$SPRING_JPA_HIBERNATE_DDL_AUTO
      - IMAGE_FOLDER=$IMAGE_FOLDER
      - URL_PATH=$URL_PATH

volumes:
  image-data: