version: '2'

services:
  db:
    container_name: demo-db
    image: 'postgres:13.1-alpine'
    env_file: ./.env
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  app:
    depends_on:
      - db
    container_name: demo-app
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    env_file: ./.env
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-db:5432/customer_db
      - SPRING_DATASOURCE_USERNAME=dbUser
      - SPRING_DATASOURCE_PASSWORD=dbPassword
      #      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
